import Head from "next/head";
import styles from "../../styles/Home.module.css";

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>asleep new webv2</div>
    </div>
  );
}
